create table biz_line_0.ecs (
    dt string comment '日期',
    shop_id bigint comment '门店id',
    shop_name string comment '门店名',
    shop_full_name string comment '门店全名',
    tenant_id bigint comment '租户ID',
    tenant_name string comment '租户名',
    brand_id bigint comment '品牌id',
    brand_name string comment '品牌名',
    district_code string comment '行政区',
    business_district_id string comment '商圈',
    latitude string comment '经度',
    longitude string comment '纬度',
    district_name string comment '行政区',
    city_code string comment '城市code',
    city_name string comment '城市名字',
    province_code string comment '省code',
    province_name string comment '省名字',
    country_code string comment '国家code',
    country_name string comment '国家名字',
    day_of_week int comment '日/周',
    day_of_month int comment '日/月',
    day_of_year int comment '日/年',
    week_of_month int comment '周/月',
    week_of_year int comment '周/年',
    month_of_year int comment '月/年',
    `year` string comment '年',
    holiday boolean comment '是否节假日',
    sku_id bigint comment 'sku id',
    sku_name string comment 'sku名字',
    spu_id bigint comment 'spu id',
    spu_name string comment 'spu名字',
    weight string comment '重量',
    volume string comment '体积',
    specifications string comment '规格',
    manufacturer string comment '生产商',
    catagory1_id bigint comment '一级类目id',
    catagory2_id bigint comment '二级类目id',
    catagory3_id bigint comment '三级类目id',
    catagory4_id bigint comment '四级类目id',
    catagory5_id bigint comment '五级类目id',
    catagory1_name string comment '一级类目',
    catagory2_name string comment '二级类目',
    catagory3_name string comment '三级类目',
    catagory4_name string comment '四级类目',
    catagory5_name string comment '五级类目',
    sale_amt decimal(38,6) comment '销售额',
    sale_cnt int comment '销量',
    refund_amt decimal(38,6) comment '退款额',
    refund_cnt int comment '退款量',
    refund_amt_rate decimal(38,6) comment '退款率',
    refund_cnt_rate decimal(38,6) comment '退货率',
    expose_pv bigint comment '曝光pv',
    expose_uv bigint comment '曝光uv',
    click_pv bigint comment '点击pv',
    click_uv bigint comment '点击uv',
    view_pv bigint comment '浏览pv',
    view_uv bigint comment '浏览uv',
    buy_pv bigint comment '购买pv',
    buy_uv bigint comment '购买uv',
    visit_buy_rate decimal(38,6) comment '访购率'
) tblproperties(
  'relate_model_ids' = '23,24,25'
) comment '电商demo数据demo';

select sum(sale_amt)/sum(buy_pv) as avg_unit_price,
       sum(sale_cnt)/sum(buy_pv) as avg_unit_cnt,
       shop_id as shop_id,
       shop_name as shop_name,
       shop_full_name as shop_full_name,
       tenant_id as tenant_id,
       tenant_name as tenant_name,
       brand_id as brand_id,
       brand_name as brand_name,
       district_code as district_code,
       business_district_id as business_district_id,
       latitude as latitude,
       longitude as longitude,
       district_name as district_name,
       city_code as city_code,
       city_name as city_name,
       province_code as province_code,
       province_name as province_name,
       country_code as country_code,
       country_name as country_name,
       day_of_month as day_of_month,
       day_of_week as day_of_week,
       day_of_year as day_of_year,
       week_of_month as week_of_month,
       week_of_year as week_of_year,
       month_of_year as month_of_year,
       `year` as year,
       holiday as holiday,
       sku_id as sku_id,
       sku_name as sku_name,
       spu_id as spu_id,
       spu_name as spu_name,
       weight as weight,
       volume as volume,
       specifications as specifications,
       manufacturer as manufacturer,
       catagory1_id as catagory1_id,
       catagory1_name as catagory1_name,
       catagory2_id as catagory2_id,
       catagory2_name as catagory2_name,
       catagory3_id as catagory3_id,
       catagory3_name as catagory3_name,
       catagory4_id as catagory4_id,
       catagory4_name as catagory4_name,
       dt as dt
      from biz_line_0.ecs group by shop_id,
        shop_name,
        shop_full_name,
        tenant_id,
        tenant_name,
        brand_id,
        brand_name,
        district_code,
        business_district_id,
        latitude,
        longitude,
        district_name,
        city_code,
        city_name,
        province_code,
        province_name,
        country_code,
        country_name,
        day_of_month,
        day_of_week,
        day_of_year,
        week_of_month,
        week_of_year,
        month_of_year,
        `year`,
        holiday,
        sku_id,
        sku_name,
        spu_id,
        spu_name,
        weight,
        volume,
        specifications,
        manufacturer,
        catagory1_id,
        catagory1_name,
        catagory2_id,
        catagory2_name,
        catagory3_id,
        catagory3_name,
        catagory4_id,
        catagory4_name,
        dt;

      select
          t1.sale_amt1/t2.sale_amt2 as sale_amt_catagory1_percentage,
          t1.sale_cnt1/t2.sale_cnt2 as sale_cnt_catagory1_percentage,
          t1.shop_id as shop_id,
          t1.shop_name as shop_name,
          t1.shop_full_name as shop_full_name,
          t1.tenant_id as tenant_id,
          t1.tenant_name as tenant_name,
          t1.brand_id as brand_id,
          t1.brand_name as brand_name,
          t1.district_code as district_code,
          t1.business_district_id as business_district_id,
          t1.latitude as latitude,
          t1.longitude as longitude,
          t1.district_name as district_name,
          t1.city_code as city_code,
          t1.city_name as city_name,
          t1.province_code as province_code,
          t1.province_name as province_name,
          t1.country_code as country_code,
          t1.country_name as country_name,
          t1.day_of_month as day_of_month,
          t1.day_of_week as day_of_week,
          t1.day_of_year as day_of_year,
          t1.week_of_month as week_of_month,
          t1.week_of_year as week_of_year,
          t1.month_of_year as month_of_year,
          t1.`year` as year,
          t1.holiday as holiday,
          t1.sku_id as sku_id,
          t1.sku_name as sku_name,
           t1.spu_id as spu_id,
           t1.spu_name as spu_name,
           t1.weight as weight,
           t1.volume as volume,
           t1.specifications as specifications,
           t1.manufacturer as manufacturer,
           t1.catagory1_id as catagory1_id,
           t1.catagory1_name as catagory1_name,
           t1.catagory2_id as catagory2_id,
           t1.catagory2_name as catagory2_name,
           t1.catagory3_id as catagory3_id,
           t1.catagory3_name as catagory3_name,
           t1.catagory4_id as catagory4_id,
           t1.catagory4_name as catagory4_name,
           t1.dt as dt
           from
        (select
               sum(sale_amt) as sale_amt1,
               sum(sale_cnt) as sale_cnt1,
               shop_id as shop_id,
               shop_name as shop_name,
               shop_full_name as shop_full_name,
               tenant_id as tenant_id,
               tenant_name as tenant_name,
               brand_id as brand_id,
               brand_name as brand_name,
               district_code as district_code,
               business_district_id as business_district_id,
               latitude as latitude,
               longitude as longitude,
               district_name as district_name,
               city_code as city_code,
               city_name as city_name,
               province_code as province_code,
               province_name as province_name,
               country_code as country_code,
               country_name as country_name,
               day_of_month as day_of_month,
               day_of_week as day_of_week,
               day_of_year as day_of_year,
               week_of_month as week_of_month,
               week_of_year as week_of_year,
               month_of_year as month_of_year,
               `year` as year,
               holiday as holiday,
               sku_id as sku_id,
               sku_name as sku_name,
               spu_id as spu_id,
               spu_name as spu_name,
               weight as weight,
               volume as volume,
               specifications as specifications,
               manufacturer as manufacturer,
               catagory1_id as catagory1_id,
               catagory1_name as catagory1_name,
               catagory2_id as catagory2_id,
               catagory2_name as catagory2_name,
               catagory3_id as catagory3_id,
               catagory3_name as catagory3_name,
               catagory4_id as catagory4_id,
               catagory4_name as catagory4_name,
               dt as dt
        from biz_line_0.ecs group by shop_id,
            shop_name,
            shop_full_name,
            tenant_id,
            tenant_name,
            brand_id,
            brand_name,
            district_code,
            business_district_id,
            latitude,
            longitude,
            district_name,
            city_code,
            city_name,
            province_code,
            province_name,
            country_code,
            country_name,
            day_of_month,
            day_of_week,
            day_of_year,
            week_of_month,
            week_of_year,
            month_of_year,
            `year`,
            holiday,
            sku_id,
            sku_name,
            spu_id,
            spu_name,
            weight,
            volume,
            specifications,
            manufacturer,
            catagory1_id,
            catagory1_name,
            catagory2_id,
            catagory2_name,
            catagory3_id,
            catagory3_name,
            catagory4_id,
            catagory4_name,
            dt) t1
            join
            (select
               sum(sale_amt) as sale_amt2,
               sum(sale_cnt) as sale_cnt2,
               shop_id as shop_id,
               shop_name as shop_name,
               shop_full_name as shop_full_name,
               tenant_id as tenant_id,
               tenant_name as tenant_name,
               brand_id as brand_id,
               brand_name as brand_name,
               city_code as city_code,
               city_name as city_name,
               province_code as province_code,
               province_name as province_name,
               country_code as country_code,
               country_name as country_name,
               day_of_month as day_of_month,
               day_of_week as day_of_week,
               day_of_year as day_of_year,
               week_of_month as week_of_month,
               week_of_year as week_of_year,
               month_of_year as month_of_year,
               `year` as year,
               holiday as holiday,
               catagory1_id as catagory1_id,
               catagory1_name as catagory1_name,
               dt as dt
        from biz_line_0.ecs group by
              shop_id,
              shop_name,
              shop_full_name,
              tenant_id,
              tenant_name,
              brand_id,
              brand_name,
              city_code,
              city_name,
              province_code,
              province_name,
              country_code,
              country_name,
              day_of_month,
              day_of_week,
              day_of_year,
              week_of_month,
              week_of_year,
              month_of_year,
              `year`,
              holiday,
              catagory1_id,
              catagory1_name,
              dt) t2 on
          t1.shop_id = t2.shop_id
          and t1.shop_name = t2.shop_name
          and t1.shop_full_name = t2.shop_full_name
          and t1.tenant_id = t2.tenant_id
          and t1.tenant_name = t2.tenant_name
          and t1.brand_id = t2.brand_id
          and t1.brand_name = t2.brand_name
          and t1.city_code = t2.city_code
          and t1.city_name = t2.city_name
          and t1.province_code = t2.province_code
          and t1.province_name = t2.province_name
          and t1.country_code = t2.country_code
          and t1.country_name = t2.country_name
          and t1.day_of_month = t2.day_of_month
          and t1.day_of_week = t2.day_of_week
          and t1.day_of_year = t2.day_of_year
          and t1.week_of_month = t2.week_of_month
          and t1.week_of_year = t2.week_of_year
          and t1.month_of_year = t2.month_of_year
          and t1.`year` = t2.`year`
          and t1.holiday = t2.holiday
          and t1.catagory1_id = t2.catagory1_id
          and t1.catagory1_name = t2.catagory1_name
          and t1.dt = t2.dt;