create table t10000_xy_mysql.trade_shop_dt
comment '门店交易数据'
as
select
    t1.dt as dt,
    t1.shop_id as shop_id,
    t2.shop_name as shop_name,
    t2.shop_full_name as shop_full_name,
    t2.tenant_id as tenant_id,
    t2.tenant_name as tenant_name,
    t2.brand_id as brand_id,
    t2.brand_name as brand_name,
    t2.ditrict_code as ditrict_code,
    t2.business_district_id as business_district_id,
    t2.latitude as latitude,
    t2.longitude as longitude,
    t3.district_name as district_name,
    t3.city_code as city_code,
    t3.city_name as city_name,
    t3.province_code as province_code,
    t3.province_name as province_name,
    t3.country_code as country_code,
    t3.country_name as country_name,
    t4.day_of_week as day_of_week,
    t4.day_of_month as day_of_month,
    t4.day_of_year as day_of_year,
    t4.week_of_month as week_of_month,
    t4.week_of_year as week_of_year,
    t4.month_of_year as month_of_year,
    t4.year as `year`,
    t4.holiday as holidy,
    sum(t1.sale_amt) as sale_amt,
    sum(t1.sale_cnt) as sale_cnt,
    sum(t1.refund_amt) as refund_amt,
    sum(t1.refund_cnt) as refund_cnt,
    sum(t1.fee) as fee
from xy_ec_demo_flow.dws_trade_shop_d_ss t1
         left join xy_ec_demo_flow.dim_shop_ss t2 on t1.shop_id = t2.shop_id and t1.dt = t2.dt
         left join xy_ec_demo_flow.dim_city_ss t3 on t2.district_code = t3.district_code and t2.dt = t3.dt
         left join xy_ec_demo_flow.dim_dt_ss t4 on t1.dt = t4.dt
group by
    t1.dt,
    t1.shop_id,
    t2.shop_name,
    t2.shop_full_name,
    t2.tenant_id,
    t2.tenant_name,
    t2.brand_id,
    t2.brand_name,
    t2.ditrict_code,
    t2.business_district_id,
    t2.latitude,
    t2.longitude,
    t3.district_name,
    t3.city_code,
    t3.city_name,
    t3.province_code,
    t3.province_name,
    t3.country_code,
    t3.country_name,
    t4.day_of_week,
    t4.day_of_month,
    t4.day_of_year,
    t4.week_of_month,
    t4.week_of_year,
    t4.month_of_year,
    t4.year ,
    t4.holiday