package com.xy.fedex.admin.service.dsn.model.po;

import java.io.Serializable;
import java.util.Date;

public class DsnPO implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsn.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsn.dsn
     *
     * @mbg.generated
     */
    private String dsn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsn.db_type
     *
     * @mbg.generated
     */
    private String dbType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsn.connect_info
     *
     * @mbg.generated
     */
    private String connectInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsn.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsn.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsn.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dsn
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsn.id
     *
     * @return the value of dsn.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsn.id
     *
     * @param id the value for dsn.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsn.dsn
     *
     * @return the value of dsn.dsn
     *
     * @mbg.generated
     */
    public String getDsn() {
        return dsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsn.dsn
     *
     * @param dsn the value for dsn.dsn
     *
     * @mbg.generated
     */
    public void setDsn(String dsn) {
        this.dsn = dsn == null ? null : dsn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsn.db_type
     *
     * @return the value of dsn.db_type
     *
     * @mbg.generated
     */
    public String getDbType() {
        return dbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsn.db_type
     *
     * @param dbType the value for dsn.db_type
     *
     * @mbg.generated
     */
    public void setDbType(String dbType) {
        this.dbType = dbType == null ? null : dbType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsn.connect_info
     *
     * @return the value of dsn.connect_info
     *
     * @mbg.generated
     */
    public String getConnectInfo() {
        return connectInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsn.connect_info
     *
     * @param connectInfo the value for dsn.connect_info
     *
     * @mbg.generated
     */
    public void setConnectInfo(String connectInfo) {
        this.connectInfo = connectInfo == null ? null : connectInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsn.status
     *
     * @return the value of dsn.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsn.status
     *
     * @param status the value for dsn.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsn.create_time
     *
     * @return the value of dsn.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsn.create_time
     *
     * @param createTime the value for dsn.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsn.update_time
     *
     * @return the value of dsn.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsn.update_time
     *
     * @param updateTime the value for dsn.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    public String getCreator() {
        return creator;
    }

    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DsnPO other = (DsnPO) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getDsn() == null ? other.getDsn() == null : this.getDsn().equals(other.getDsn()))
            && (this.getDbType() == null ? other.getDbType() == null : this.getDbType().equals(other.getDbType()))
            && (this.getConnectInfo() == null ? other.getConnectInfo() == null : this.getConnectInfo().equals(other.getConnectInfo()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getCreator() == null ? other.getCreator() == null : this.getCreator().equals(other.getCreator()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getDsn() == null) ? 0 : getDsn().hashCode());
        result = prime * result + ((getDbType() == null) ? 0 : getDbType().hashCode());
        result = prime * result + ((getConnectInfo() == null) ? 0 : getConnectInfo().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getCreator() == null) ? 0 : getCreator().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsn
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", dsn=").append(dsn);
        sb.append(", dbType=").append(dbType);
        sb.append(", connectInfo=").append(connectInfo);
        sb.append(", status=").append(status);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", creator=").append(creator);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}