server:
  port: 8080
dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://172.18.0.5:2181
  scan:
    base-packages: com.xy.fedex.catalog.api
  provider:
    timeout: 15000
spring:
  application:
    name: xy-fedex-catalog-service
  datasource:
    url: jdbc:mysql://172.18.0.2:3306/xy_cs?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    config:
      discovery:
        service-id: xy-fedex-catalog-service
        enabled: on

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xy.fedex.catalog.po

dubbo.server.version: 1.0.0
